Making python test write out extra information (exit code or command to diff) when failing.

diff --git a/python/testsuite/testall.in b/python/testsuite/testall.in
--- a/python/testsuite/testall.in
+++ b/python/testsuite/testall.in
@@ -47,9 +47,13 @@
 
 set -e
 
+# To see the output, you need to run:
+#     make test ARGS="-V"
+verbose=1
+
 executable=../regina-python
 testdir="@PROJECT_SOURCE_DIR@/python/testsuite"
-tmpout=test.tmp
+testoutdir=`mktemp -d`
 
 echo "---------------------------------------"
 echo "Test suite for Regina's python bindings"
@@ -57,12 +61,12 @@ echo "---------------------------------------"
 echo
 
 if ! test -f ../../CMakeCache.txt -a -f "$executable"; then
-	echo "ERROR: You do not appear to be within the python/testsuite directory"
-	echo "       in the build tree.  This script must be run from directly"
-	echo "       within the build tree (where you ran the configure script)."
-	echo "       Please change into the python/testsuite directory in the"
-	echo "       build tree and try again."
-	exit 1
+    echo "ERROR: You do not appear to be within the python/testsuite directory"
+    echo "       in the build tree.  This script must be run from directly"
+    echo "       within the build tree (where you ran the configure script)."
+    echo "       Please change into the python/testsuite directory in the"
+    echo "       build tree and try again."
+    exit 1
 fi
 
 # Clobber environment variables that the user might already have set.
@@ -72,43 +76,67 @@ export REGINA_HOME=
 
 broken=
 found=
-for i in `find "$testdir" -name "*.test" | sort`; do
-	found=1
-	testname=`basename "$i"`
-	echo -n "Running $testname ... "
 
-	output="${i/.test/.out}"
-	if ! ( TERM= "$executable" -n "$i" "$testdir" > "$tmpout" 2>&1 ); then
-		echo "COULD NOT RUN"
-		broken=1
-	else
-		if ! ( diff --strip-trailing-cr "$tmpout" "$output" > /dev/null ); then
-			echo "TEST FAILED"
-			broken=1
-		else
-			echo "ok"
-		fi
-	fi
-	rm -f "$tmpout"
+for i in `find "$testdir" -name "*.test" | sort`; do
+    found=1
+    testname=`basename "$i"`
+    baseline="${i/.test/.out}"
+    testout="$testoutdir/${testname/.test/.out}"
+    echo -n "Running $testname ... "
+
+    # Run test
+    # Since we have "set -e", we need "&& dummy=" to prevent this line to just
+    # exit the bash script when the test has non-zero exit code
+    "$executable" -n "$i" "$testdir" > "$testout" 2>&1 && dummy=
+
+    # Catch exitcode
+    exitcode=$?
+
+    # Branch based on exit code
+    if [ $exitcode -ne 0 ];  then
+        echo "FAILED (exit code $exitcode)"
+        if test -n "$verbose"; then
+            echo "    command was:"
+            echo "        " \""$executable"\" "-n" \""$i"\" \""$testdir"\" ">" \""$testout"\" "2>&1"
+            echo "    output was:"
+            echo "        ..."
+            tail -n 5 $testout | sed 's/^/        /'
+        fi
+        broken=1
+    else
+        if ! ( diff --strip-trailing-cr "$testout" "$baseline" > /dev/null ); then
+            echo "FAILED (output differs from expected)"
+            if test -n "$verbose"; then
+                echo "    command to diff:"
+                echo "        " diff "--strip-trailing-cr" \""$testout"\" \""$baseline"\"
+            fi
+            broken=1
+        else
+            echo "ok"
+            rm -f "$testout"
+        fi
+    fi
 done
 
 if ! test -n "$found"; then
-	echo "ERROR: No tests were found!"
-	echo
-	echo "       Please check your installation, and please ensure that"
-	echo "       you are running this script from within the python/testsuite"
-	echo "       directory of the build tree."
-	echo
-	echo "       Note that the build tree might not be the same as the source"
-	echo "       tree.  The build tree is where you ran the configure script."
-	exit 1
+    echo "ERROR: No tests were found!"
+    echo
+    echo "       Please check your installation, and please ensure that"
+    echo "       you are running this script from within the python/testsuite"
+    echo "       directory of the build tree."
+    echo
+    echo "       Note that the build tree might not be the same as the source"
+    echo "       tree.  The build tree is where you ran the configure script."
+    exit 1
 fi
 
 if test -n "$broken"; then
-	echo
-	echo "One or more tests failed."
-	echo "Please see the list above for details."
-	exit 1
+    echo
+    echo "One or more tests failed."
+    echo "Please see the list above for details."
+    exit 1
+else
+    rmdir "$testoutdir"
 fi
 
 echo
