Some infrastructure for the python policy transition.

diff --git a/debian/sid/pycheck b/debian/sid/pycheck
--- a/debian/sid/pycheck
+++ b/debian/sid/pycheck
@@ -3,14 +3,15 @@
 # Python version checker for Regina.
 #
 # Ensures that python versions are consistent between the binaries
-# (specifically, the compiled python module regina.so) and the
-# regina-python startup script.
+# (specifically, the compiled python module regina.so), the
+# regina-python startup script, and the debian control file.
 #
 # For use during the final stage of the debian package build.
 #
 set -e
 
 tmp=debian/tmp
+control=debian/control
 python_script=/usr/bin/regina-python
 python_script_src=python/regina-python
 python_lib=/usr/lib/regina-normal/python/regina.so
@@ -22,6 +23,9 @@ pyver_script=`grep 'python[0-9]\.[0-9]' $tmp$python_script | \
 
 pyver_lib=`ldd $tmp$python_lib | grep 'libpython[0-9]\.[0-9]\.so' | \
   sed -e 's/^.*libpython\([0-9]\.[0-9]\).so.*$/\1/'`
+
+pyver_control=`grep ^XS-Python-Version $control | \
+  sed -e 's/^XS-Python-Version: //'`
 
 case "$pyver_script" in
   ?.? )
@@ -43,6 +47,16 @@ case "$pyver_lib" in
     ;;
 esac
 
+case "$pyver_control" in
+  ?.? )
+    # Okay; we expect something of the form X.Y.
+    ;;
+  * )
+    echo "ERROR: Could not determine the python version specified in $control."
+    exit 1
+    ;;
+esac
+
 if ! test "$pyver_script" = "$pyver_lib"; then
   echo
   echo "ERROR: Mismatched python versions between binaries and startup script."
@@ -53,6 +67,18 @@ if ! test "$pyver_script" = "$pyver_lib"; then
   echo "       This can be fixed in the sources by changing the python version "
   echo "           number in $python_script_src and $python_script_src.in"
   echo "           (find the section where \$which_python is initialised)."
+  exit 1
+fi
+
+if ! test "$pyver_lib" = "$pyver_control"; then
+  echo
+  echo "ERROR: Mismatched python versions between binaries and $control."
+  echo
+  echo "       $python_lib uses python$pyver_lib."
+  echo "       $control specifies python$pyver_control."
+  echo
+  echo "       This can be fixed in the sources by changing the"
+  echo "           XS-Python-Version field in $control."
   exit 1
 fi
 
