Replaced tabs with spaces.

diff --git a/scripts/regscript_misc b/scripts/regscript_misc
--- a/scripts/regscript_misc
+++ b/scripts/regscript_misc
@@ -11,9 +11,9 @@ read_regscript_misc=1
 # Classpath separator.
 # This should be ":" under linux/unix environments and ";" under windows.
 if [ "$OSTYPE" = "cygwin" ]; then
-	cps=";"
+    cps=";"
 else
-	cps=":"
+    cps=":"
 fi
 
 # Address to which questions should be emailed.
@@ -25,19 +25,19 @@ support="regina-user@lists.sourceforge.net"
 # Usage: testvalue <value> <variable_name> <value1> [ <value2> ... ]
 # Return: 0 if the variable has one of the given values, 1 otherwise.
 testvalue () {
-	value="$1"
-	variable_name="$2"
-	list=""
-	shift 2
-	for v do
-		if [ "$value" = "$v" ]; then
-			return 0
-		fi
-		list="$list \"$v\""
-	done
-	warn "Warning: Variable \$$variable_name was set to \"$value\"."
-	warn "         It must be one of:$list"
-	return 1
+    value="$1"
+    variable_name="$2"
+    list=""
+    shift 2
+    for v do
+        if [ "$value" = "$v" ]; then
+            return 0
+        fi
+        list="$list \"$v\""
+    done
+    warn "Warning: Variable \$$variable_name was set to \"$value\"."
+    warn "         It must be one of:$list"
+    return 1
 }
 
 # ---------- Environment Variable Defaults ----------
@@ -47,18 +47,18 @@ testvalue () {
 # Use default if nothing is specified.
 default_verbosity=1
 if [ -z "$REGINA_VERBOSITY" ]; then
-	export REGINA_VERBOSITY=1
+    export REGINA_VERBOSITY=1
 fi
 
 # Check it's an appropriate value.
 case "$REGINA_VERBOSITY" in
-	[012] )
-	;;
-	* )
-		error "Error: \$REGINA_VERBOSITY should be 0, 1 or 2."
-		error "       (0 = errors, 1 = errors/warnings, 2 = everything)"
-		exit 1
-	;;
+    [012] )
+    ;;
+    * )
+        error "Error: \$REGINA_VERBOSITY should be 0, 1 or 2."
+        error "       (0 = errors, 1 = errors/warnings, 2 = everything)"
+        exit 1
+    ;;
 esac
 
 # ---------- Export current variables ----------
diff --git a/scripts/regscript_opt b/scripts/regscript_opt
--- a/scripts/regscript_opt
+++ b/scripts/regscript_opt
@@ -18,22 +18,22 @@ runtime_options=regina.conf
 # Use default if nothing is specified.
 default_options_global="/etc/$REGINA_PACKAGE"
 if [ -z "$REGINA_OPTIONS_GLOBAL" ]; then
-	export REGINA_OPTIONS_GLOBAL="$default_options_global"
+    export REGINA_OPTIONS_GLOBAL="$default_options_global"
 fi
 
 # Use nothing if it's not a directory.
 if [ ! -z "$REGINA_OPTIONS_GLOBAL" ]; then
-	if [ ! -d "$REGINA_OPTIONS_GLOBAL" ]; then
-		warn "Warning: $REGINA_OPTIONS_GLOBAL is not a directory."
-		export REGINA_OPTIONS_GLOBAL=
-	fi
+    if [ ! -d "$REGINA_OPTIONS_GLOBAL" ]; then
+        warn "Warning: $REGINA_OPTIONS_GLOBAL is not a directory."
+        export REGINA_OPTIONS_GLOBAL=
+    fi
 fi
 
 # Warn the user if we have no global options directory.
 if [ -z "$REGINA_OPTIONS_GLOBAL" ]; then
-	warn "Warning: No global options directory."
+    warn "Warning: No global options directory."
 else
-	info "-- Global options directory (REGINA_OPTIONS_GLOBAL): $REGINA_OPTIONS_GLOBAL"
+    info "-- Global options directory (REGINA_OPTIONS_GLOBAL): $REGINA_OPTIONS_GLOBAL"
 fi
 
 # --- Local options directory ---
@@ -41,215 +41,215 @@ fi
 # Use default if nothing is specified.
 # Make sure we work around old shells that don't understand ~.
 if [ ! -z "$HOME" ]; then
-	default_options_local="`echo "$HOME/.regina"`"
+    default_options_local="`echo "$HOME/.regina"`"
 else
-	default_options_local="`echo ~/.regina`"
+    default_options_local="`echo ~/.regina`"
 fi
 if [ -z "$REGINA_OPTIONS_LOCAL" ]; then
-	export REGINA_OPTIONS_LOCAL="$default_options_local"
+    export REGINA_OPTIONS_LOCAL="$default_options_local"
 fi
 
 # If it does exist, use nothing if it's not a directory.
 # If it doesn't exist, try to create it.
 if [ ! -z "$REGINA_OPTIONS_LOCAL" ]; then
-	if [ ! -e "$REGINA_OPTIONS_LOCAL" ]; then
-		if ! mkdir "$REGINA_OPTIONS_LOCAL"; then
-			warn "Warning: $REGINA_OPTIONS_LOCAL could not be created."
-			export REGINA_OPTIONS_LOCAL=
-		fi
-	elif [ ! -d "$REGINA_OPTIONS_LOCAL" ]; then
-		warn "Warning: $REGINA_OPTIONS_LOCAL is not a directory."
-		export REGINA_OPTIONS_LOCAL=
-	fi
+    if [ ! -e "$REGINA_OPTIONS_LOCAL" ]; then
+        if ! mkdir "$REGINA_OPTIONS_LOCAL"; then
+            warn "Warning: $REGINA_OPTIONS_LOCAL could not be created."
+            export REGINA_OPTIONS_LOCAL=
+        fi
+    elif [ ! -d "$REGINA_OPTIONS_LOCAL" ]; then
+        warn "Warning: $REGINA_OPTIONS_LOCAL is not a directory."
+        export REGINA_OPTIONS_LOCAL=
+    fi
 fi
 
 # Warn the user if we have no local options directory.
 if [ -z "$REGINA_OPTIONS_LOCAL" ]; then
-	warn "Warning: No local options directory."
+    warn "Warning: No local options directory."
 else
-	info "-- Local options directory (REGINA_OPTIONS_LOCAL): $REGINA_OPTIONS_LOCAL"
+    info "-- Local options directory (REGINA_OPTIONS_LOCAL): $REGINA_OPTIONS_LOCAL"
 fi
 
 # ---------- Read options files ----------
 
 # Read the local runtime options file.
 if [ ! -z "$REGINA_OPTIONS_LOCAL" ]; then
-	options="$REGINA_OPTIONS_LOCAL/$runtime_options"
-	if [ -f "$options" ]; then
-		optioncmds=`awk -f "$REGINA_HOME/scripts/regscript_readopts" "$options"`
-		eval $optioncmds;
-	elif [ -e "$options" ]; then
-		warn "Warning: Options file [$options] is not a regular file."
-	else
-		warn "Warning: No local runtime options file [$options]."
-	fi
+    options="$REGINA_OPTIONS_LOCAL/$runtime_options"
+    if [ -f "$options" ]; then
+        optioncmds=`awk -f "$REGINA_HOME/scripts/regscript_readopts" "$options"`
+        eval $optioncmds;
+    elif [ -e "$options" ]; then
+        warn "Warning: Options file [$options] is not a regular file."
+    else
+        warn "Warning: No local runtime options file [$options]."
+    fi
 fi
 
 # Read the global runtime options file.
 if [ ! -z "$REGINA_OPTIONS_GLOBAL" ]; then
-	options="$REGINA_OPTIONS_GLOBAL/$runtime_options"
-	if [ -f "$options" ]; then
-		optioncmds=`awk -f "$REGINA_HOME/scripts/regscript_readopts" "$options"`
-		eval $optioncmds;
-	elif [ -e "$options" ]; then
-		warn "Warning: Options file [$options] is not a regular file."
-	else
-		warn "Warning: No global runtime options file [$options]."
-	fi
+    options="$REGINA_OPTIONS_GLOBAL/$runtime_options"
+    if [ -f "$options" ]; then
+        optioncmds=`awk -f "$REGINA_HOME/scripts/regscript_readopts" "$options"`
+        eval $optioncmds;
+    elif [ -e "$options" ]; then
+        warn "Warning: Options file [$options] is not a regular file."
+    else
+        warn "Warning: No global runtime options file [$options]."
+    fi
 fi
 
 # ---------- Set defaults and run sanity checks ----------
 
 if [ -z "$REGINA_BTOOLS" ]; then
-	export REGINA_BTOOLS="`ls "$REGINA_HOME"/jar/btools*.jar 2> /dev/null`"
-	if [ -z "$REGINA_BTOOLS" ]; then
-		export REGINA_BTOOLS="$REGINA_HOME/jar/btools.jar"
-	fi
+    export REGINA_BTOOLS="`ls "$REGINA_HOME"/jar/btools*.jar 2> /dev/null`"
+    if [ -z "$REGINA_BTOOLS" ]; then
+        export REGINA_BTOOLS="$REGINA_HOME/jar/btools.jar"
+    fi
 fi
 if [ -d "$REGINA_BTOOLS" ]; then
-	error "Error: \$REGINA_BTOOLS is set to a directory, not a file."
-	error "       It should be set to the full pathname of the BTools jar file."
-	error "       For example: REGINA_BTOOLS=/usr/share/java/btools.jar"
-	error "       Please fix this setting and try again."
-	exit 1
+    error "Error: \$REGINA_BTOOLS is set to a directory, not a file."
+    error "       It should be set to the full pathname of the BTools jar file."
+    error "       For example: REGINA_BTOOLS=/usr/share/java/btools.jar"
+    error "       Please fix this setting and try again."
+    exit 1
 elif [ ! -e "$REGINA_BTOOLS" ]; then
-	error "Error: The BTools library could not be found."
-	error "       Set \$REGINA_BTOOLS to the location of btools.jar"
-	error "       and try again."
-	exit 1
+    error "Error: The BTools library could not be found."
+    error "       Set \$REGINA_BTOOLS to the location of btools.jar"
+    error "       and try again."
+    exit 1
 fi
 
 if [ -z "$REGINA_JYTHON" ]; then
-	export REGINA_JYTHON="`ls "$REGINA_HOME"/jar/jython*.jar 2> /dev/null`"
-	if [ -z "$REGINA_JYTHON" ]; then
-		export REGINA_JYTHON="$REGINA_HOME/jar/jython.jar"
-	fi
+    export REGINA_JYTHON="`ls "$REGINA_HOME"/jar/jython*.jar 2> /dev/null`"
+    if [ -z "$REGINA_JYTHON" ]; then
+        export REGINA_JYTHON="$REGINA_HOME/jar/jython.jar"
+    fi
 fi
 if [ -d "$REGINA_JYTHON" ]; then
-	warn "Warning: \$REGINA_JYTHON is set to a directory, not a file."
-	warn "         It should be set to the full pathname of the Jython jar file."
-	warn "         For example: REGINA_JYTHON=/usr/share/java/jython.jar"
-	warn "         Scripting will not be available until this is fixed."
+    warn "Warning: \$REGINA_JYTHON is set to a directory, not a file."
+    warn "         It should be set to the full pathname of the Jython jar file."
+    warn "         For example: REGINA_JYTHON=/usr/share/java/jython.jar"
+    warn "         Scripting will not be available until this is fixed."
 elif [ ! -e "$REGINA_JYTHON" ]; then
-	warn "Warning: The Jython library could not be found."
-	warn "         Scripting will not be available."
-	warn "         To fix this, set \$REGINA_JYTHON to the location"
-	warn "         of jython.jar and try again."
+    warn "Warning: The Jython library could not be found."
+    warn "         Scripting will not be available."
+    warn "         To fix this, set \$REGINA_JYTHON to the location"
+    warn "         of jython.jar and try again."
 fi
 
 if [ -z "$REGINA_JAVAHELP" ]; then
-	export REGINA_JAVAHELP="`ls "$REGINA_HOME"/jar/jh.jar 2> /dev/null`"
-	if [ -z "$REGINA_JAVAHELP" ]; then
-		export REGINA_JAVAHELP="$REGINA_HOME/jar/jh.jar"
-	fi
+    export REGINA_JAVAHELP="`ls "$REGINA_HOME"/jar/jh.jar 2> /dev/null`"
+    if [ -z "$REGINA_JAVAHELP" ]; then
+        export REGINA_JAVAHELP="$REGINA_HOME/jar/jh.jar"
+    fi
 fi
 if [ -d "$REGINA_JAVAHELP" ]; then
-	warn "Warning: \$REGINA_JAVAHELP is set to a directory, not a file."
-	warn "         It should be set to the full pathname of the JavaHelp jar file."
-	warn "         For example: REGINA_JAVAHELP=/usr/share/java/jh.jar"
-	warn "         The built-in help browser will not be available until"
-	warn "         this is fixed."
+    warn "Warning: \$REGINA_JAVAHELP is set to a directory, not a file."
+    warn "         It should be set to the full pathname of the JavaHelp jar file."
+    warn "         For example: REGINA_JAVAHELP=/usr/share/java/jh.jar"
+    warn "         The built-in help browser will not be available until"
+    warn "         this is fixed."
 elif [ ! -e "$REGINA_JAVAHELP" ]; then
-	warn "Warning: The JavaHelp library could not be found."
-	warn "         The built-in help browser will not be available."
-	warn "         To fix this, set \$REGINA_JAVAHELP to the location"
-	warn "         of jh.jar and try again."
+    warn "Warning: The JavaHelp library could not be found."
+    warn "         The built-in help browser will not be available."
+    warn "         To fix this, set \$REGINA_JAVAHELP to the location"
+    warn "         of jh.jar and try again."
 fi
 
 if [ -z "$REGINA_JAVA" ]; then
-	# Take the Java runtime from the path.
-	export REGINA_JAVA=`which java`
-	if [ -z "$REGINA_JAVA" ]; then
-		error "Error: A Java runtime could not be found."
-		error "       Set \$REGINA_JAVA to a Java runtime (such as /usr/bin/java)"
-		error "       and try again."
-		exit 1
-	fi
+    # Take the Java runtime from the path.
+    export REGINA_JAVA=`which java`
+    if [ -z "$REGINA_JAVA" ]; then
+        error "Error: A Java runtime could not be found."
+        error "       Set \$REGINA_JAVA to a Java runtime (such as /usr/bin/java)"
+        error "       and try again."
+        exit 1
+    fi
 fi
 
 if [ -z "$REGINA_JNIDIR" ]; then
-	if [ "$REGINA_FROMSOURCE" = "1" ]; then
-		export REGINA_JNIDIR="$REGINA_HOME/engine/jni/.libs:/usr/lib"
-	else
-		_grandparent="`cd "$REGINA_HOME"/../.. && pwd`"
-		export REGINA_JNIDIR="$_grandparent/lib/$REGINA_PACKAGE:/usr/lib"
-	fi
+    if [ "$REGINA_FROMSOURCE" = "1" ]; then
+        export REGINA_JNIDIR="$REGINA_HOME/engine/jni/.libs:/usr/lib"
+    else
+        _grandparent="`cd "$REGINA_HOME"/../.. && pwd`"
+        export REGINA_JNIDIR="$_grandparent/lib/$REGINA_PACKAGE:/usr/lib"
+    fi
 fi
 if [ -z "$REGINA_JNIENGINE" ]; then
-	jnilib="regina-engine-jni"
+    jnilib="regina-engine-jni"
 else
-	jnilib="$REGINA_JNIENGINE"
+    jnilib="$REGINA_JNIENGINE"
 fi
 if [ "$OSTYPE" = "cygwin" ]; then
-	jnilib="$jnilib.dll"
+    jnilib="$jnilib.dll"
 else
-	jnilib="lib$jnilib.so"
+    jnilib="lib$jnilib.so"
 fi
 # Look for the JNI library in each colon-separated component of $REGINA_JNIDIR.
 foundlib=0
 IFS=:
 for i in $REGINA_JNIDIR; do
-	if [ -e "$i/$jnilib" ]; then
-		foundlib=1
-	fi
+    if [ -e "$i/$jnilib" ]; then
+        foundlib=1
+    fi
 done
 IFS=
 if [ "$foundlib" = "0" ]; then
-	warn "Warning: The JNI library could not be found."
-	warn "         The JNI calculation engine will not be available."
-	warn "         To fix this, set \$REGINA_JNIDIR to the directory"
-	warn "         containing $jnilib and try again."
+    warn "Warning: The JNI library could not be found."
+    warn "         The JNI calculation engine will not be available."
+    warn "         To fix this, set \$REGINA_JNIDIR to the directory"
+    warn "         containing $jnilib and try again."
 fi
 
 if [ -z "$REGINA_JARDIR" ]; then
-	if [ "$REGINA_FROMSOURCE" = "1" ]; then
-		export REGINA_JARDIR="$REGINA_HOME/javaui"
-	else
-		export REGINA_JARDIR="$REGINA_HOME/jar"
-	fi
+    if [ "$REGINA_FROMSOURCE" = "1" ]; then
+        export REGINA_JARDIR="$REGINA_HOME/javaui"
+    else
+        export REGINA_JARDIR="$REGINA_HOME/jar"
+    fi
 fi
 if [ ! -e "$REGINA_JARDIR/$REGINA_PACKAGE.jar" ]; then
-	error "Error: The Regina jar directory could not be found."
-	error "       Set \$REGINA_JARDIR to the directory containing regina.jar"
-	error "       and try again."
-	exit 1
+    error "Error: The Regina jar directory could not be found."
+    error "       Set \$REGINA_JARDIR to the directory containing regina.jar"
+    error "       and try again."
+    exit 1
 fi
 
 if [ -z "$REGINA_CACHEDIR" ]; then
-	if [ ! -z "$REGINA_OPTIONS_LOCAL" ]; then
-		export REGINA_CACHEDIR="$REGINA_OPTIONS_LOCAL/cache"
-	fi
+    if [ ! -z "$REGINA_OPTIONS_LOCAL" ]; then
+        export REGINA_CACHEDIR="$REGINA_OPTIONS_LOCAL/cache"
+    fi
 fi
 if [ ! -z "$REGINA_CACHEDIR" ]; then
-	if [ ! -e "$REGINA_CACHEDIR" ]; then
-		if ! mkdir "$REGINA_CACHEDIR"; then
-			warn "Warning: $REGINA_CACHEDIR could not be created."
-			export REGINA_CACHEDIR=
-		fi
-	elif [ ! -d "$REGINA_CACHEDIR" ]; then
-		warn "Warning: $REGINA_CACHEDIR is not a directory."
-		export REGINA_CACHEDIR=
-	fi
+    if [ ! -e "$REGINA_CACHEDIR" ]; then
+        if ! mkdir "$REGINA_CACHEDIR"; then
+            warn "Warning: $REGINA_CACHEDIR could not be created."
+            export REGINA_CACHEDIR=
+        fi
+    elif [ ! -d "$REGINA_CACHEDIR" ]; then
+        warn "Warning: $REGINA_CACHEDIR is not a directory."
+        export REGINA_CACHEDIR=
+    fi
 fi
 if [ -z "$REGINA_CACHEDIR" ]; then
-	warn "Warning: You have no Jython cache directory."
-	warn "         You may not be able to use Jython scripting, or you may"
-	warn "         find a \"package\" directory inadvertently created in the"
-	warn "         current directory (which is safe to delete)."
-	warn "         To fix this problem, set \$REGINA_CACHEDIR to a cache"
-	warn "         directory to which you have write access and try again."
+    warn "Warning: You have no Jython cache directory."
+    warn "         You may not be able to use Jython scripting, or you may"
+    warn "         find a \"package\" directory inadvertently created in the"
+    warn "         current directory (which is safe to delete)."
+    warn "         To fix this problem, set \$REGINA_CACHEDIR to a cache"
+    warn "         directory to which you have write access and try again."
 fi
 
 if [ ! -z "$REGINA_ENGINE" ]; then
-	if ! testvalue "$REGINA_ENGINE" REGINA_ENGINE jni; then
-		export REGINA_ENGINE=""
-	fi
+    if ! testvalue "$REGINA_ENGINE" REGINA_ENGINE jni; then
+        export REGINA_ENGINE=""
+    fi
 fi
 
 if [ ! -z "$REGINA_INTERFACE" ]; then
-	if ! testvalue "$REGINA_INTERFACE" REGINA_INTERFACE gui console text; then
-		export REGINA_INTERFACE=""
-	fi
+    if ! testvalue "$REGINA_INTERFACE" REGINA_INTERFACE gui console text; then
+        export REGINA_INTERFACE=""
+    fi
 fi
 
 # ---------- Output current options ----------
